// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package inc.roguelike.babusya.network;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inc.roguelike.babusya.network.Empty)
    com.google.protobuf.MessageOrBuilder {
}
