// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package inc.roguelike.babusya.network;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inc.roguelike.babusya.network.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string level = 1;</code>
   * @return The level.
   */
  java.lang.String getLevel();
  /**
   * <code>string level = 1;</code>
   * @return The bytes for level.
   */
  com.google.protobuf.ByteString
      getLevelBytes();

  /**
   * <code>bool ends = 2;</code>
   * @return The ends.
   */
  boolean getEnds();

  /**
   * <code>string log = 3;</code>
   * @return The log.
   */
  java.lang.String getLog();
  /**
   * <code>string log = 3;</code>
   * @return The bytes for log.
   */
  com.google.protobuf.ByteString
      getLogBytes();
}
