// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package inc.roguelike.babusya.network;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inc_roguelike_babusya_network_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inc_roguelike_babusya_network_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inc_roguelike_babusya_network_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inc_roguelike_babusya_network_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rservice.proto\022\035inc.roguelike.babusya.n" +
      "etwork\"\007\n\005Empty\"3\n\007Message\022\r\n\005level\030\001 \001(" +
      "\t\022\014\n\004ends\030\002 \001(\010\022\013\n\003log\030\003 \001(\t2\305\001\n\004Game\022`\n" +
      "\016receiveMessage\022$.inc.roguelike.babusya." +
      "network.Empty\032&.inc.roguelike.babusya.ne" +
      "twork.Message0\001\022[\n\013sendMessage\022&.inc.rog" +
      "uelike.babusya.network.Message\032$.inc.rog" +
      "uelike.babusya.network.EmptyB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_inc_roguelike_babusya_network_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_inc_roguelike_babusya_network_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inc_roguelike_babusya_network_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_inc_roguelike_babusya_network_Message_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_inc_roguelike_babusya_network_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inc_roguelike_babusya_network_Message_descriptor,
        new java.lang.String[] { "Level", "Ends", "Log", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
